---
abstract: 'Automatically set a flag in the environment if a mobile client is detected'
author:
  - 'Heiko Jansen <hjansen@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-DetectMobileBrowsers
requires:
  Plack: 0
resources:
  repository: https://github.com/heikojansen/plack-middleware-detectmobilebrowsers.git
version: 0.02
